services:
  mahasiswa_read:
    build: ./mahasiswa_read
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./mahasiswa_read/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=postgresql://kenta:kentaganteng123@mahasiswa_db/mahasiswa
    depends_on:
      - mahasiswa_db

  mahasiswa_update:
    build: ./mahasiswa_update
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./mahasiswa_update/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://kenta:kentaganteng123@mahasiswa_db/mahasiswa
    depends_on:
      - mahasiswa_db
  
  mahasiswa_db:
    image: postgres:14
    volumes:
      - postgres_data_mahasiswa:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kenta
      - POSTGRES_PASSWORD=kentaganteng123
      - POSTGRES_DB=mahasiswa

  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mahasiswa_read
      - mahasiswa_update

volumes:
  postgres_data_mahasiswa: